/* Contenuto della pagina Missioni: una missione per ogni posto
   dell'itinerario. Tenuto separato dal rendering come js/content.js.

   Una missione è:
   { id, day, stars, icon, title, location, desc, game: { title, items }, bonus? }
   più, se non vale per tutti:
   - optional: true      → facoltativa
   - choice: 'testo'     → solo se scegliete quell'opzione dell'itinerario
   Le missioni facoltative o a scelta danno stelle bonus e non contano nel
   totale da raggiungere.

   Un item del gioco è una stringa, oppure una frase da dire in inglese:
   { it, en, say }. */
window.MISSIONS = {
  hero: {
    badge: '🎯 Gioco per il weekend',
    title: 'Le <em>Missioni</em> di Londra',
    subtitle:
      'Per ogni posto che visitiamo c’è una missione. Apri la scheda, spunta quello che trovi e conquista le stelle!',
    starsLabel: 'Stelle conquistate:',
  },
  rules: [
    '👀 Ogni missione ha una lista di cose da trovare o da fare.',
    '✅ Per completarla serve almeno metà delle caselle: più ne spunti, più stelle prendi.',
    '📱 I progressi restano salvati su questo telefono, anche se chiudi la pagina.',
  ],
  ui: {
    sectionTitle: 'Le {count} missioni',
    sectionIntro: '{bonus} sono facoltative o dipendono dall’opzione che scegliete: danno stelle bonus.',
    missionStars: '⭐ {stars} stelle',
    optionalBadge: '🌟 Facoltativa',
    choiceBadge: '🔀 Se scegliete: {choice}',
    gameProgress: '{done}/{total}',
    audioLabel: 'Ascolta in inglese: {word}',
    btnComplete: '🏆 Completa la missione!',
    btnDoneFull: '✅ Missione completata! +{stars} stelle',
    btnDonePartial: '✅ Missione completata! +{stars}/{max} stelle ({done}/{total} caselle)',
    btnUndo: '✖ Annulla',
    thresholdError: '🚫 Spunta almeno {min} caselle su {total} per completare la missione: ne hai {have}.',
    allDone: '🎉 Tutte le missioni principali completate! Siete veri esploratori di Londra.',
    toolsTitle: 'I miei progressi',
    btnBackupSave: '💾 Salva una copia',
    btnBackupLoad: '📂 Carica una copia',
    btnReset: '🔄 Ricomincia da capo',
    resetConfirm: 'Sicuro di voler azzerare tutte le stelle e le missioni?',
    backupLoaded: 'Progressi caricati! 🎉',
    backupLoadError: 'Non riesco a leggere questo file.',
    storageWarning:
      '⚠️ Il salvataggio automatico non funziona su questo browser (navigazione privata?): i progressi andranno persi chiudendo la pagina.',
  },
  days: [
    { id: 'always', label: '🎒 Per tutto il weekend' },
    { id: 'sat', label: '🦕 Sabato 6 dicembre · Musei, parco + Harrods' },
    { id: 'sun', label: '🌉 Domenica 7 dicembre · a seconda dell’opzione' },
    { id: 'mon', label: '✨ Lunedì 8 dicembre · Luci di Natale' },
  ],
  missions: [
    /* ── Sempre ─────────────────────────────────────────────── */
    {
      id: 'simboli',
      day: 'always',
      stars: 120,
      icon: '🇬🇧',
      title: 'La Caccia ai Simboli di Londra',
      location: '📍 Ovunque, per tutto il weekend',
      desc: 'Londra è piena di cose che si trovano solo qui. Tenete gli occhi aperti dal primo all’ultimo giorno!',
      game: {
        title: '🎮 Il tuo gioco · Avvistamenti',
        items: [
          'Un autobus rosso a due piani 🚌',
          'Una cabina telefonica rossa ☎️',
          'Un taxi nero, il «black cab» 🚕',
          'Una cassetta delle lettere rossa con la corona 📮',
          'Un poliziotto con il cappello alto a cupola 👮',
          'La bandiera del Regno Unito, la Union Jack 🇬🇧',
          'Il cartello «Mind the gap» in metropolitana 🚇',
          'Uno scoiattolo grigio in un parco 🐿️',
        ],
      },
      bonus: '✨ Sfida bonus: prima di partire scommettete quanti autobus rossi vedrete nel weekend. Chi si avvicina di più vince!',
    },
    {
      id: 'inglese',
      day: 'always',
      optional: true,
      stars: 70,
      icon: '💬',
      title: 'Le Parole Magiche in Inglese',
      location: '📍 Ovunque: al ristorante, nei negozi, sul bus',
      desc: 'Prova a dire queste frasi a una persona vera: un cameriere, un commesso, l’autista del bus. Premi 🔊 per sentire come si pronunciano.',
      game: {
        title: '🎮 Il tuo gioco · Parla come un londinese',
        items: [
          { it: 'Ciao!', en: 'Hello!', say: 'hel-lòu' },
          { it: 'Per favore', en: 'Please', say: 'pliiz' },
          { it: 'Grazie mille!', en: 'Thank you very much!', say: 'thènk-iu vèri mac' },
          { it: 'Mi scusi', en: 'Excuse me', say: 'ex-kiùs mi' },
          { it: 'Una cioccolata calda, per favore', en: 'A hot chocolate, please', say: 'a hot ciòc-let, pliiz' },
          { it: 'Quanto costa?', en: 'How much is it?', say: 'hàu mac is it' },
          { it: 'Buon Natale!', en: 'Merry Christmas!', say: 'mèri crìs-mas' },
        ],
      },
    },

    /* ── Sabato ─────────────────────────────────────────────── */
    {
      id: 'dinosauri',
      day: 'sat',
      stars: 150,
      icon: '🦕',
      title: 'Il Cacciatore di Dinosauri',
      location: '📍 Natural History Museum · South Kensington',
      desc: 'Un museo che sembra una cattedrale, con animali scolpiti nella pietra sui muri. Nella grande sala d’ingresso, la Hintze Hall, vi aspetta lo scheletro di una balenottera azzurra appeso al soffitto: si chiama Hope ed è lunga 25 metri!',
      game: {
        title: '🎮 Il tuo gioco · Caccia al fossile',
        items: [
          'Hope, la balena appesa nella Hintze Hall 🐋',
          'Il T. rex che si muove e ruggisce 🦖',
          'Un uovo di dinosauro 🥚',
          'La scala mobile che entra dentro un enorme globo della Terra 🌍',
          'Un animale scolpito nella pietra sui muri o sulle colonne 🐒',
          'Un meteorite, una pietra caduta dallo spazio ☄️',
          'Un animale che non esiste più 🦤',
        ],
      },
      bonus: '✨ Sfida bonus: inventa un dinosauro tutto tuo (nome, cosa mangia, quanto è grande) e disegnalo.',
    },
    {
      id: 'spezie',
      day: 'sat',
      optional: true,
      stars: 50,
      icon: '🍛',
      title: 'L’Esploratore delle Spezie',
      location: '📍 Dishoom South Kensington (o South Kensington Kitchen)',
      desc: 'Dishoom è ispirato ai vecchi caffè di Bombay, in India. Il pranzo è anche un piccolo viaggio: assaggia con coraggio!',
      game: {
        title: '🎮 Il tuo gioco · Assaggi coraggiosi',
        items: [
          'Assaggiare il naan, il pane indiano cotto nel forno 🫓',
          'Trovare una spezia che pizzica sulla lingua 🌶️',
          'Bere un sorso di chai o di lassi 🥛',
          'Chiedere cosa vuol dire una parola strana del menù 📜',
          'Trovare una vecchia foto appesa alle pareti 🖼️',
        ],
      },
    },
    {
      id: 'scienza',
      day: 'sat',
      stars: 150,
      icon: '🚀',
      title: 'Lo Scienziato in Missione',
      location: '📍 Science Museum · Exhibition Road',
      desc: 'Qui ci sono macchine vere che hanno cambiato il mondo: motori a vapore enormi, razzi e perfino una capsula che è andata intorno alla Luna.',
      game: {
        title: '🎮 Il tuo gioco · Il laboratorio segreto',
        items: [
          'La capsula Apollo 10, andata davvero intorno alla Luna 🌕',
          'Un motore a vapore gigante 🚂',
          'Un razzo o un satellite 🛰️',
          'Una macchina che fai muovere tu, con un bottone o una leva 🕹️',
          'Un’invenzione che usi anche tu ogni giorno 💡',
          'Un oggetto più vecchio della bisnonna ⏳',
        ],
      },
      bonus: '✨ Sfida bonus: inventa una macchina che fa i compiti al posto tuo. Spiega a mamma e papà come funziona in 30 secondi!',
    },
    {
      id: 'parco',
      day: 'sat',
      optional: true,
      stars: 150,
      icon: '🦢',
      title: 'L’Esploratore del Parco',
      location: '📍 Kensington Gardens e Hyde Park · fino a Knightsbridge',
      desc: 'Al posto del Science Museum, si attraversa il parco più famoso di Londra a piedi. Qui vive Peter Pan, il bambino che non voleva crescere!',
      game: {
        title: '🎮 Il tuo gioco · La mappa del tesoro',
        items: [
          'L’Albert Memorial, la statua tutta d’oro ✨',
          'La statua di Peter Pan 🧚',
          'Un cigno bianco sul lago 🦢',
          'Uno scoiattolo grigio 🐿️',
          'La nave dei pirati del Diana Memorial Playground 🏴‍☠️',
          'Un cane con il cappottino 🐕',
        ],
      },
      bonus: '✨ Sfida bonus: contate i cigni che vedete sul Serpentine. Chi indovina il numero prima di arrivare al lago vince!',
    },
    {
      id: 'bus74',
      day: 'sat',
      optional: true,
      stars: 50,
      icon: '🚌',
      title: 'Il Capitano del Double-Decker',
      location: '📍 Bus 74 · da South Kensington a Knightsbridge',
      desc: 'Il viaggio è corto, ma dal piano di sopra di un bus rosso Londra si vede come da una torre.',
      game: {
        title: '🎮 Il tuo gioco · Il posto migliore',
        items: [
          'Salire al piano di sopra 🪜',
          'Conquistare un posto davanti, con la vista migliore 👀',
          'Contare i bus rossi incrociati 🔢',
          'Premere il pulsante per prenotare la fermata 🔔',
          'Vedere Harrods dal finestrino 🏬',
        ],
      },
    },
    {
      id: 'harrods',
      day: 'sat',
      stars: 120,
      icon: '🎁',
      title: 'Gli Elfi di Harrods',
      location: '📍 Harrods · Christmas World al piano -1 · Knightsbridge',
      desc: 'Harrods è uno dei grandi magazzini più famosi del mondo. A Natale il Christmas World è pieno di palline, alberi e giocattoli: sembra il laboratorio di Babbo Natale.',
      game: {
        title: '🎮 Il tuo gioco · Il laboratorio degli elfi',
        items: [
          'La scala mobile egizia, con statue e geroglifici 🏺',
          'L’orsetto di peluche di Natale di quest’anno 🧸',
          'Una pallina per l’albero a forma di cibo o di animale 🎄',
          'L’albero di Natale più alto del negozio 🌲',
          'Qualcuno con la borsa verde di Harrods 🛍️',
          'Le vetrine di Natale viste da fuori 🪟',
        ],
      },
      bonus: '✨ Sfida bonus: se poteste portare a casa una sola decorazione, quale scegliereste? Votate in famiglia!',
    },
    {
      id: 'mercatino',
      day: 'sat',
      stars: 100,
      icon: '🎄',
      title: 'Il Re del Mercatino',
      location: '📍 Mercatino di Natale (quello che scegliete)',
      desc: 'Casette di legno, lucine e profumo di dolci: il mercatino è il posto perfetto per sentirsi già a Natale.',
      game: {
        title: '🎮 Il tuo gioco · Giro delle bancarelle',
        items: [
          'Una casetta di legno con le lucine 🏠',
          'Un omino di pan di zenzero 🍪',
          'Le caldarroste (segui il profumo!) 🌰',
          'Babbo Natale o un suo aiutante 🎅',
          'Una bancarella con qualcosa che non hai mai visto 🤔',
          'Ordinare da solo una cioccolata calda in inglese ☕',
        ],
      },
      bonus: '✨ Sfida bonus: scegli la bancarella più bella del mercatino e spiega perché.',
    },

    /* ── Domenica (dipende dall'opzione) ───────────────────── */
    {
      id: 'tate',
      day: 'sun',
      choice: 'Opzione 1 o 3',
      stars: 120,
      icon: '🎨',
      title: 'Il Detective dell’Arte Moderna',
      location: '📍 Tate Modern · Bankside',
      desc: 'Una volta era una centrale elettrica: la ciminiera altissima c’è ancora! Dentro, la Turbine Hall è così grande che ci stanno opere gigantesche. Dalla terrazza in alto si vede mezza Londra.',
      game: {
        title: '🎮 Il tuo gioco · Indagine al museo',
        items: [
          'La ciminiera della vecchia centrale elettrica 🏭',
          'L’opera nella Turbine Hall: descrivila in tre parole 🏛️',
          'Un quadro che sembra uno scarabocchio, ma è famoso 🖍️',
          'Un’opera fatta con oggetti di tutti i giorni 🪑',
          'Un quadro tutto di un solo colore 🟥',
          'Dalla terrazza: la cupola di St Paul’s e il fiume 🔭',
        ],
      },
      bonus: '✨ Sfida bonus: scegli l’opera più strana e inventale un titolo migliore.',
    },
    {
      id: 'ponte',
      day: 'sun',
      choice: 'Opzione 1 o 3',
      stars: 80,
      icon: '🌉',
      title: 'Il Ponte Traballante',
      location: '📍 Millennium Bridge · tra Tate Modern e St Paul’s',
      desc: 'Quando l’hanno aperto, nel 2000, il ponte oscillava così tanto sotto i passi della gente che l’hanno chiuso subito per aggiustarlo. I londinesi lo chiamano ancora «the Wobbly Bridge», il ponte traballante.',
      game: {
        title: '🎮 Il tuo gioco · Sul ponte',
        items: [
          'Attraversare tutto il ponte a piedi 🚶',
          'La foto con la cupola di St Paul’s in fondo al ponte 📸',
          'Un battello che passa sotto il ponte ⛴️',
          'Le gomme da masticare dipinte per terra sul ponte 🎨',
          'Contare quanti altri ponti si vedono sul fiume 🔢',
        ],
      },
    },
    {
      id: 'borough',
      day: 'sun',
      choice: 'Domenica opzione 1 o 3, oppure Lunedì Tower Bridge',
      stars: 100,
      icon: '🧺',
      title: 'L’Assaggiatore del Mercato',
      location: '📍 Borough Market · London Bridge',
      desc: 'Uno dei mercati del cibo più antichi di Londra, sotto tettoie di ferro e vetro, proprio accanto ai binari del treno.',
      game: {
        title: '🎮 Il tuo gioco · Il palato d’oro',
        items: [
          'Una forma di formaggio grande come una ruota 🧀',
          'Assaggiare qualcosa che non hai mai mangiato 😋',
          'Un treno che passa sopra il mercato 🚆',
          'La bancarella con la coda più lunga 🧍',
          'Un frutto o una verdura dal nome strano 🥕',
          'Il dolce che vorresti portare a casa 🍰',
        ],
      },
    },
    {
      id: 'southbank',
      day: 'sun',
      choice: 'Opzione 1 o 3',
      stars: 90,
      icon: '🎡',
      title: 'Le Luci sul Tamigi',
      location: '📍 Southbank Centre Winter Market',
      desc: 'Il mercatino lungo il fiume, con il London Eye da una parte e il Big Ben dall’altra. Quando fa buio le luci si riflettono sull’acqua.',
      game: {
        title: '🎮 Il tuo gioco · Lungo il fiume',
        items: [
          'Il London Eye, la grande ruota panoramica 🎡',
          'Il Big Ben dall’altra parte del fiume 🕰️',
          'Una giostra o un’attrazione di Natale 🎠',
          'Gli skater sotto il Southbank Centre 🛹',
          'Le luci che si riflettono sull’acqua ✨',
          'Un artista di strada 🎶',
        ],
      },
    },
    {
      id: 'greenwich',
      day: 'sun',
      choice: 'Opzione 2',
      stars: 150,
      icon: '⚓',
      title: 'Il Guardiano del Tempo',
      location: '📍 Cutty Sark, Royal Observatory e Greenwich Park',
      desc: 'A Greenwich passa il Meridiano zero, la linea da cui si contano le ore di tutto il mondo: puoi stare con un piede a est e uno a ovest! Il Cutty Sark era uno dei velieri più veloci del suo tempo e portava il tè dalla Cina.',
      game: {
        title: '🎮 Il tuo gioco · A cavallo del mondo',
        items: [
          'Il veliero Cutty Sark ⛵',
          'Un piede a est e uno a ovest sul Meridiano 0° 🦶',
          'La palla rossa sul tetto dell’Osservatorio (scende ogni giorno alle 13:00) 🔴',
          'Il grande orologio vicino al cancello dell’Osservatorio 🕐',
          'Londra vista dalla collina del parco 🏙️',
          'Uno scoiattolo o un cervo nel Greenwich Park 🦌',
        ],
      },
      bonus: '✨ Sfida bonus: che ore sono adesso dall’altra parte del mondo, in Australia? Prova a indovinare, poi controllate.',
    },
    {
      id: 'battello',
      day: 'sun',
      choice: 'Opzione 2',
      stars: 80,
      icon: '⛴️',
      title: 'Il Capitano del Tamigi',
      location: '📍 Battello da Greenwich a Westminster o Tower Pier',
      desc: 'Dal fiume Londra si vede tutta in fila: ponti, torri e palazzi che si accendono quando fa buio.',
      game: {
        title: '🎮 Il tuo gioco · Diario di bordo',
        items: [
          'Il Tower Bridge visto dall’acqua 🌉',
          'Lo Shard, il grattacielo a punta di vetro 🏙️',
          'Contare i ponti sotto cui passate 🔢',
          'Un gabbiano che segue il battello 🐦',
          'Il London Eye dal fiume 🎡',
          'Le luci della città che si accendono 🌃',
        ],
      },
    },

    /* ── Lunedì ─────────────────────────────────────────────── */
    {
      id: 'wonderland',
      day: 'mon',
      choice: 'Winter Wonderland (mattina)',
      stars: 120,
      icon: '🎡',
      title: 'L’Avventuriero di Winter Wonderland',
      location: '📍 Hyde Park Winter Wonderland',
      desc: 'Il grande luna park di Natale dentro Hyde Park. Di lunedì mattina c’è poca gente: è il momento giusto!',
      game: {
        title: '🎮 Il tuo gioco · Giro delle giostre',
        items: [
          'La ruota panoramica gigante 🎡',
          'La pista di pattinaggio sul ghiaccio ⛸️',
          'Le casette in stile bavarese 🏘️',
          'Una giostra che fa urlare la gente 🎢',
          'Un pupazzo di neve o un orso polare (finto!) ⛄',
          'Uno spuntino caldo: churros, crêpe o wurstel 🌭',
        ],
      },
    },
    {
      id: 'towerbridge',
      day: 'mon',
      choice: 'Tower Bridge (mattina)',
      stars: 120,
      icon: '🌉',
      title: 'Il Funambolo di Tower Bridge',
      location: '📍 Tower Bridge Exhibition',
      desc: 'Il Tower Bridge si apre in due per far passare le navi alte! Nella mostra si cammina sulle passerelle in alto, con un pavimento di vetro sotto i piedi.',
      game: {
        title: '🎮 Il tuo gioco · Sopra il fiume',
        items: [
          'Camminare sul pavimento di vetro 🫣',
          'Una barca che passa sotto il ponte ⛵',
          'La Torre di Londra, il castello sulla riva 🏰',
          'Le vecchie macchine a vapore che alzavano il ponte ⚙️',
          'Lo Shard visto dall’alto 🏙️',
          'Una foto riflessa nel soffitto a specchio 🪞',
        ],
      },
    },
    {
      id: 'stpauls',
      day: 'mon',
      stars: 100,
      icon: '⛪',
      title: 'Il Segreto della Cupola',
      location: '📍 St Paul’s Cathedral al tramonto',
      desc: 'La cupola di St Paul’s è una delle più grandi del mondo. Durante la Seconda guerra mondiale la cattedrale è sopravvissuta ai bombardamenti. Dentro c’è la Galleria dei Sussurri: una parola sussurrata contro il muro si sente dall’altra parte!',
      game: {
        title: '🎮 Il tuo gioco · Al calar del sole',
        items: [
          'La cupola che si illumina quando fa buio 🌆',
          'La statua della regina davanti alla cattedrale 👑',
          'Contare le colonne della facciata 🏛️',
          'I piccioni sulla scalinata 🐦',
          'Il cielo che diventa arancione o rosa 🌇',
          'Se entrate alle 17:00, ascoltare il coro in silenzio 🎶',
        ],
      },
    },
    {
      id: 'luci',
      day: 'mon',
      stars: 150,
      icon: '✨',
      title: 'Il Cacciatore di Luci',
      location: '📍 Oxford Street → Regent Street → Carnaby Street',
      desc: 'Ogni anno le vie del centro si riempiono di luci giganti. Con il buio sono ancora più belle, e di lunedì c’è molta meno gente.',
      game: {
        title: '🎮 Il tuo gioco · Caccia alla luce',
        items: [
          'Gli angeli di luce sopra Regent Street 👼',
          'Le decorazioni di Carnaby Street (cambiano ogni anno!) 🎉',
          'La vetrina più bella di Oxford Street 🪟',
          'Un bus rosso che passa sotto le luci 🚌',
          'Qualcuno vestito da Babbo Natale 🎅',
          'Contare gli alberi di Natale lungo la strada 🎄',
        ],
      },
      bonus: '✨ Sfida bonus: scattate una foto di famiglia sotto le luci più belle della serata.',
    },
    {
      id: 'hamleys',
      day: 'mon',
      stars: 120,
      icon: '🧸',
      title: 'Il Collaudatore di Hamleys',
      location: '📍 Hamleys · 188–196 Regent Street',
      desc: 'Hamleys è nato nel 1760 ed è uno dei negozi di giocattoli più antichi del mondo. Tanti piani pieni di giochi, e i commessi fanno vedere come funzionano!',
      game: {
        title: '🎮 Il tuo gioco · Prova giocattoli',
        items: [
          'Un commesso che fa la dimostrazione di un gioco 🪀',
          'Il peluche più grande del negozio 🧸',
          'Una scultura fatta di LEGO 🧱',
          'Un gioco che c’era già quando mamma e papà erano piccoli 🕹️',
          'Il gioco da scrivere nella lettera a Babbo Natale ✉️',
          'Tutti i piani visitati, dal più basso al più alto 🛗',
        ],
      },
    },
    {
      id: 'finale',
      day: 'mon',
      optional: true,
      stars: 60,
      icon: '🍨',
      title: 'Il Gran Finale Dolce',
      location: '📍 Cena a Carnaby e dolce da Kaspa’s',
      desc: 'L’ultima sera del weekend. Prima di tornare a casa, un dolce e un po’ di ricordi.',
      game: {
        title: '🎮 Il tuo gioco · I ricordi del weekend',
        items: [
          'Scegliere il dolce con il nome più lungo 🍨',
          'Dire «Merry Christmas!» a chi vi serve 🎄',
          'Votare il posto più bello del weekend 🏆',
          'Raccontare la cosa più buffa successa a Londra 😂',
        ],
      },
    },
  ],
};
